// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMKxYfvkblXOlxZVVCS9w7vZ8Zah-s7A0',
    appId: '1:1003354957439:web:8276117e7d8fbe9604c14a',
    messagingSenderId: '1003354957439',
    projectId: 'eventstracker-8339f',
    authDomain: 'eventstracker-8339f.firebaseapp.com',
    storageBucket: 'eventstracker-8339f.appspot.com',
    measurementId: 'G-K5XX6K0ZLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqb0o7HmRoKQKPk5EG0xuDZAhQOF82WtQ',
    appId: '1:1003354957439:android:3eafe7493531987904c14a',
    messagingSenderId: '1003354957439',
    projectId: 'eventstracker-8339f',
    storageBucket: 'eventstracker-8339f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLEmhZgT3PPnc0G5QHEvFI1-nKHuoHHn8',
    appId: '1:1003354957439:ios:b73bca75b728662804c14a',
    messagingSenderId: '1003354957439',
    projectId: 'eventstracker-8339f',
    storageBucket: 'eventstracker-8339f.appspot.com',
    iosClientId: '1003354957439-aeveh97o5qbioc0h6h6c5r81m1h11uh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventstracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLEmhZgT3PPnc0G5QHEvFI1-nKHuoHHn8',
    appId: '1:1003354957439:ios:c60fd9c6f4565efd04c14a',
    messagingSenderId: '1003354957439',
    projectId: 'eventstracker-8339f',
    storageBucket: 'eventstracker-8339f.appspot.com',
    iosClientId: '1003354957439-bu8nj23j2096nar4h6l65dovsp54ijkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventstracker.RunnerTests',
  );
}
